version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: .
    restart: always
    environment:
      DATABASE_URL: "postgresql://root:example@postgres:5432/my_database"  # Note: 'postgres' is the service name here
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:






